# docker-compose.yml
# This file is used to define and manage multi-container Docker applications.
# It uses the Docker Compose format version 3.

# The version field specifies the Docker Compose file format version.
# In this case, it is set to '3', which is the latest version.
version: '3'

# The services field defines the services that will be run in the Docker application.
# Each service is defined as a key-value pair, where the key is the service name and the value is an object containing the service configuration.
services:
  # The 'app' service is defined here.
  # It is configured to build a Docker image using the Dockerfile in the current directory.
  # The 'build' key specifies the build configuration for the service.
  # The 'image' key specifies the name of a docker image that we intend to build.
  # The 'context' field specifies the context for the build, which is the directory containing the Dockerfile.
  # The 'dockerfile' field specifies the path to the Dockerfile within the context directory.
  app:
    image: gcrdeploy
    container_name: gcrdeploy-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

    # The 'ports' field specifies the ports that the service will expose.
    # In this case, the 'app' service will expose port 2345 on the host machine.
    ports:
      - '2345:2345'

    # The 'environment' field specifies the environment variables that will be set for the service.
    # In this case, the 'PORT' environment variable is set to 2345.
    environment:
      PORT: 2345
