apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
spec:
  selector:
    matchLabels:
      app: nestjs
  replicas: 1
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: musigwa/nestjs
          ports:
            - containerPort: 3000
